fix: comments on SOQL files only allowed at BOF
forcedotcom/apex-tmLanguage pull request #41
Opened 2021-01-29 15:00 UTC by dobladez

Before:

https://user-images.githubusercontent.com/152839/106290678-7de0d580-6229-11eb-97bb-db61b3567964.mov

After:

https://user-images.githubusercontent.com/152839/106290726-8802d400-6229-11eb-864b-e5a4ed5d1d45.mov

2021-01-29 19:55 UTC, sfsholden commented
@dobladez Could you please expand on what you mean by BOF? I'm unclear why this change was needed. Please also include the work item in the description so future developers can get further context if needed.

2021-01-29 20:14 UTC, dobladez commented
> @dobladez Could you please expand on what you mean by BOF? I'm unclear why this change was needed. Please also include the work item in the description so future developers can get further context if needed.

Sorry, I meant "beginning of file". I've changed the description. Also added the WIs. Thanks

2021-01-29 21:43 UTC, praksb approved these changes

2021-02-01 16:15 UTC, sfsholden approved these changes

2021-02-01 18:26 UTC, lcampos commented on grammars/soql.tmLanguage
> +      <key>soqlHeaderComment</key>
This should be added directly to `soql.tmLanguage.template.yml` since the `.tmLanguage` files are a result of compiling the `*.yml`.

2021-02-01 18:27 UTC, lcampos requested changes
Should address the comment on `soql.tmLanguage`

2021-02-01 18:51 UTC, dobladez commented on grammars/soql.tmLanguage
> +      <key>soqlHeaderComment</key>
The change is already on `src/soql.tmLanguage.template.yml`. Am I missing something?

2021-02-01 19:17 UTC, lcampos commented on grammars/soql.tmLanguage
> +      <key>soqlHeaderComment</key>
My bad, I completely missed those changes

2021-02-01 19:17 UTC, lcampos approved these changes

2021-02-01 22:26 UTC, merged